I'm sorry, but an uncaught exception occurred.

While running game code:
IOError: [Errno 13] Permission denied: 'C:\\Users\\User\\AppData\\Roaming/RenPy/To The Nudes-1498941698\\persistent.tmp'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\User\Desktop\renpy-6.99.12.2-sdk\renpy\bootstrap.py", line 290, in bootstrap
    renpy.main.main()
  File "C:\Users\User\Desktop\renpy-6.99.12.2-sdk\renpy\main.py", line 490, in main
    renpy.persistent.update(True)
  File "C:\Users\User\Desktop\renpy-6.99.12.2-sdk\renpy\persistent.py", line 378, in update
    save()
  File "C:\Users\User\Desktop\renpy-6.99.12.2-sdk\renpy\persistent.py", line 393, in save
    renpy.loadsave.location.save_persistent(data)
  File "C:\Users\User\Desktop\renpy-6.99.12.2-sdk\renpy\savelocation.py", line 463, in save_persistent
    l.save_persistent(data)
  File "C:\Users\User\Desktop\renpy-6.99.12.2-sdk\renpy\savelocation.py", line 327, in save_persistent
    with open(fn_tmp, "wb") as f:
IOError: [Errno 13] Permission denied: 'C:\\Users\\User\\AppData\\Roaming/RenPy/To The Nudes-1498941698\\persistent.tmp'

Windows-7-6.1.7601-SP1
Ren'Py 6.99.12.2.2029
To The Nudes 0.000
